apps/frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.index, name='index'),
    path('analytics/', views.analytics_view, name='analytics'),
    path('visit-count/<str:page_url>/', views.get_visit_count, name='visit-count'),
]

django_main/urls.py
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django_main.settings import MEDIA_ROOT
from rest_framework.routers import DefaultRouter
from frontend.views import LoginView, RegisterView, Profile_edit, LogoutView, get_visit_count
from frontend.proj_views import RefereeRecordsView, update_ref_data
from article.views import ArticleViewSet, CategoryViewSet, TagViewSet, AvatarViewSet
from article.userviews import UserViewSet
from comment.views import CommentViewSet
from django.conf import settings
from django.conf.urls.static import static

try:
    from django_main.settings import STATIC_ROOT
except:
    from django_main.settings import STATICFILES_DIRS
    STATIC_ROOT = STATICFILES_DIRS[0]

router = DefaultRouter()
router.register(r'user', UserViewSet, basename='user')
router.register(r'article', ArticleViewSet)
router.register(r'category', CategoryViewSet)
router.register(r'tag', TagViewSet)
router.register(r'avatar', AvatarViewSet)
router.register(r'comment', CommentViewSet)


urlpatterns = [
    path('admin/', admin.site.urls, name="djangoadmin"),
    path('api/visit-count/article/<str:page_url>/', get_visit_count, name='article-visit-count'),
    path('api/visit-count/home/', get_visit_count, name='home-visit-count'),
    path('api/', include(router.urls)),
    path('api/article/', include('article.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('', include('frontend.urls', namespace='frontend')),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('edit/<int:id>/', Profile_edit.as_view(), name='edit'),
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),
    re_path(r'^api/(?P<version>\w+)/', include('api.urls')),
    path('rr/', RefereeRecordsView.as_view(), name="referee_records"),
    path('update-ref-data/', update_ref_data, name='update_ref_data'),
]

# # 在开发环境下，将所有未匹配的 URL 重定向到前端开发服务器
# if settings.DEBUG:
#     urlpatterns += [
#         re_path(r'^blog/.*$', TemplateView.as_view(template_name='index.html')),
#         re_path(r'^.*$', TemplateView.as_view(template_name='index.html')),
#     ]

handler404 = 'frontend.views.custom_404'
# 把媒体文件的路由注册了
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Jiayu Wang{% endblock %}</title>
  <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon"/>
  <link rel="stylesheet" href="{% static 'css/bootstrap.v4.4.1.min.css' %}">
  <link
    href="https://fonts.googleapis.com/css2?family=Kadwa&display&family=Lora&family=Bree+Serif&family=Roboto:wght@300&family=Teko:wght@300&display=swap"
    rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/hover.css' %}">
  {#    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">#}
  <link rel="stylesheet" href="{% static 'md_css/monokai_custom.css' %}">
  {#  <link rel="stylesheet" href="{% static 'md_css/manni.css' %}">#}
  {#    <link rel="stylesheet" href="{% static 'md_css/perldoc.css' %}">#}

  <!-- 添加 pyecharts 依赖 -->
  <script src="https://cdn.bootcdn.net/ajax/libs/echarts/5.4.3/echarts.min.js"></script>
  <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

  <style>
    html, body {
      min-height: 100vh;
        margin: 0;
        display: flex;
        flex-direction: column;

    }

    main {
        flex: 1;
    }

    [lang^="en"] body {
      font-family: 'Roboto', sans-serif!important;
    }

    [lang^="zh"] body {
      Font-family: 'Microsoft YaHei', '微软雅黑', Helvetica, Arial,
      sans-serif !important
    }

    a:link {
      color: #f8c04f;
      text-decoration: none;
    }

    a:visited {
      color: rgba(8, 197, 255, 0.57);
    }

    .badge {
      color: #e9f6f9 !important;
    }

    a:hover {
     opacity: 0.6;
    }

    a:active {
      background-color: skyblue;
      color: white;
    }

    #wrapper {
      min-height: 91%;
      display: flex;
      flex-direction: column;
    }

    footer {
        background-color: #333;
        color: white;
        padding: 10px 0;
        width: 100%;
        margin-top: auto;
        font-size: 12px;
    }

    .clear {
      clear: both
    }

    .navbar-nav {
      color: white !important;
    }

    .codehilite {
      padding: 10px 10px 0.5px 10px;
      margin: 6px;
      margin-bottom: 20px;
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    }

    .navbar-custom {
      color: white;
      font-size: 12px;
      font-family: 'Kadwa', serif;
    }

    .navbar-nav a.nav-link{
      color: #edffef !important;
    }

    code {
      color: rgba(182, 66, 0, 0.84);
    }

    .carousel-item img {
     height: 160px
    }

    @media (max-width: 640px){

      #fp_main_row{
        margin: 1px auto;
      }


      #jw_profile{
        margin-left: 60px;
      }

      #main-block{
        padding-left: 3px!important;
        padding-right: 3px!important;
        max-width: 100%!important;
      }
      .sidebar{
        display: none;
      }
    }


  </style>

{% block css %}{% endblock css %}
  {% block custom_head %}{% endblock %}
  <script data-name="BMC-Widget" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="jiayuwang"
          data-description="Support me on Buy me a coffee!"
          data-message="Thank you for visiting. Mind if buying me a coffee?" data-color="#79D6B5" data-position="left"
          data-x_margin="6" data-y_margin="6"></script>
</head>
<body>

{% include 'header.html' %}
<div id="wrapper">
  <main style="flex: 1">
   {% block content %}{% endblock content %}
  </main>
  <div id="push" class="mb-5"></div>
</div>
{% include 'footer.html' %}
{% block custom_js %}{% endblock %}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script src="{% static 'js/jquery.v321.min.js' %}"></script>
{% include 'back_to_top_func.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<!-- 引入bootstrap的js文件 -->
<script src="{% static 'js/bootstrap4.4.1.min.js' %}"></script>
<script src="{% static 'layer/layer.js' %}"></script>
<script src="{% static 'js/FontAwesomeKit_202003.js' %}"></script>

{% block script %}{% endblock script %}

<script async src="https://www.googletagmanager.com/gtag/js?id=G-01GV60BYGQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-01GV60BYGQ');


  jQuery('.twitter-block').delegate('#twitter-widget-0', 'DOMSubtreeModified propertychange', function () {
    //function call to override the base twitter styles
    customizeTweetMedia();
  });

  var customizeTweetMedia = function () {

    //overrides font styles and removes the profile picture and media from twitter feed


 
    jQuery('.twitter-block').find('.twitter-timeline').contents().find('p.timeline-Tweet-text').css('font-size', '16px');
    jQuery('.twitter-block').find('.twitter-timeline').contents().find('p.timeline-Tweet-text').css('font-family', 'Teko');
    jQuery('.twitter-block').find('.twitter-timeline').contents().find('span.TweetAuthor-name').css('font-size', '14px');

    //also call the function on dynamic updates in addition to page load
    jQuery('.twitter-block').find('.twitter-timeline').contents().find('.timeline-TweetList').bind('DOMSubtreeModified propertychange', function () {
      customizeTweetMedia(this);
    });
  }


  !function () {
    function n(n, e, t) {
      return n.getAttribute(e) || t
    }

    function e(n) {
      return document.getElementsByTagName(n)
    }

    function t() {
      var t = e("script"), o = t.length, i = t[o - 1];
      return {l: o, z: n(i, "zIndex", -1), o: n(i, "opacity", .5), c: n(i, "color", "0,0,0"), n: n(i, "count", 99)}
    }

    function o() {
      a = m.width = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth, c = m.height = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight
    }

    function i() {
      r.clearRect(0, 0, a, c);
      var n, e, t, o, m, l;
      s.forEach(function (i, x) {
        for (i.x += i.xa, i.y += i.ya, i.xa *= i.x > a || i.x < 0 ? -1 : 1, i.ya *= i.y > c || i.y < 0 ? -1 : 1, r.fillRect(i.x - .5, i.y - .5, 1, 1), e = x + 1; e < u.length; e++) n = u[e], null !== n.x && null !== n.y && (o = i.x - n.x, m = i.y - n.y, l = o * o + m * m, l < n.max && (n === y && l >= n.max / 2 && (i.x -= .03 * o, i.y -= .03 * m), t = (n.max - l) / n.max, r.beginPath(), r.lineWidth = t / 2, r.strokeStyle = "rgba(" + d.c + "," + (t + .2) + ")", r.moveTo(i.x, i.y), r.lineTo(n.x, n.y), r.stroke()))
      }), x(i)
    }

    var a, c, u, m = document.createElement("canvas"), d = t(), l = "c_n" + d.l, r = m.getContext("2d"),
      x = window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function (n) {
        window.setTimeout(n, 1e3 / 45)
      }, w = Math.random, y = {x: null, y: null, max: 2e4};
    m.id = l, m.style.cssText = "position:fixed;top:0;left:0;z-index:" + d.z + ";opacity: 0.1", e("body")[0].appendChild(m), o(), window.onresize = o, window.onmousemove = function (n) {
      n = n || window.event, y.x = n.clientX, y.y = n.clientY
    }, window.onmouseout = function () {
      y.x = null, y.y = null
    };
    for (var s = [], f = 0; d.n > f; f++) {
      var h = w() * a, g = w() * c, v = 2 * w() - 1, p = 2 * w() - 1;
      s.push({x: h, y: g, xa: v, ya: p, max: 6e3})
    }
    u = s.concat([y]), setTimeout(function () {
      i()
    }, 100)
  }();


  $(window).on('resize', function() {
    var win = $(this);
    if (win.width() < 640) {

      $('#main-block').addClass('col-11');
      $('#main-block').removeClass('col-9');

    } else {
      $('#main-block').addClass('col-9');
      $('#main-block').removeClass('col-11');
    }
  });


</script>
</body>
</html>

templates/footer.html
{% load static %}
{#<div>#}
{#  <br><br><br>#}
{#</div>#}
<footer class="py-2 bg-primary" id="footer">
  <div class="container">
    <p class="m-0 text-center text-white">&copy; 2007 -
      <script language="javascript" type="text/javascript">
        var today = new Date()
        var year = today.getFullYear()
        document.write(year)
      </script>

       <a href="http://www.wangjiayu.net">Jiayu Wang</a>. All Rights Reserved.
    </p>
  </div>
</footer>

templates/header.html
{% load static %}


<nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-custom">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="pt-1 navbar-brand" href="{% url 'frontend:index' %}" style="font-size: 14px; font-family: Consolas, monaco, monospace;">
      <img src="{% static 'img/jwlogo2sm.png' %}" class="border border-warning rounded-circle" style="width:40px;">&nbsp;
      <i class="fas fa-terminal"></i>
      <span style="color:rgba(159,255,94,0.92); font-size: 10px;">me@Server</span><span>:</span><span style="color:rgba(255,225,126,0.92); font-size: 8px;">~ $</span>&nbsp;<span style="font-size: 10px; color:#d0d0d0;">export NAME=</span><span style="font-weight: bold">JW</span></a>

    <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">

        <li class="nav-item"><a class="nav-link" href="/blog/">Blog</a></li>
        <li class="nav-item"><a class="nav-link" href="http://www.sommersydnie.com/games/" target="_blank">Soccer Schedule</a></li>

        {% if user.is_superuser %}
          <li class="nav-item"><a class="nav-link" href="/admin/">Admin</a></li>
        {% endif %}


        {% if user.is_authenticated %}
          <!-- 如果用户已经登录，则显示用户名下拉框 -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">



              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">


              <a class="dropdown-item" href='{% url "edit" user.id %}'>Profile</a>


              <a class="dropdown-item" href="{% url "logout" %}">Logout</a>

            </div>
          </li>
          <!-- 如果用户未登录，则显示 “登录” -->

        {% endif %} 

      </ul>
    </div>

  </div>
</nav>